name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AIRFLOW_HOME: /home/runner/work/workflows/workflows
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-airflow.txt -r requirements.txt -r requirements-test.txt
      - name: Create S3 Buckets
        run: make buckets
      - name: Run services for IT Tests
        run: make start
      - name: Run tests with pytest and generate report
        run: pytest --cov=./ --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true
